version: "3.4"

services:

  collector:
    container_name: collector
    image: collector:1.0
    command: -env-file=/home/conf/.env
    volumes:
      - ./conf:/home/conf

  preprocessor:
    container_name: preprocessor
    image: preprocessor:1.0
    command: -env-file=/home/conf/.env
    volumes:
      - ./conf:/home/conf

  archiver:
    container_name: archiver
    image: archiver:1.0
    command: -env-file=/home/conf/.env
    volumes:
      - ./conf:/home/conf
